# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('describe', models.TextField(max_length=600)),
                ('type', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2017, 11, 30, 10, 30, 2, 889598, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2017, 11, 30, 10, 30, 2, 889649, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('event', models.ManyToManyField(to='event.Event')),
            ],
        ),
    ]
