# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 38, 22, 732480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 38, 22, 732434, tzinfo=utc)),
        ),
    ]
