# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2017, 10, 31, 19, 0, 31, 718661, tzinfo=utc))),
                ('eventType', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
